# App {{{

[app]
overall = { fg = "#a6cbe6", bg = "#0b0f11" }

# }}}


# Manager {{{

[mgr]
cwd = { fg = "#dadeff" }

# Find
find_keyword  = { fg = "#dadeff", bold = true, italic = true, underline = true }
find_position = { fg = "#a6cbe6", bg = "#0b0f11", bold = true, italic = true }

# Symlink
symlink_target = { fg = "#dfe6ed", italic = true }

# Marker
marker_copied   = { fg = "#a6cbe6", bg = "#a6cbe6" }
marker_cut      = { fg = "#dadeff", bg = "#dadeff" }
marker_marked   = { fg = "#dadeff", bg = "#dadeff" }
marker_selected = { fg = "#dadeff", bg = "#dadeff" }
marker_symbol   = "│"

# Count
count_copied   = { fg = "#dfe6ed", bg = "#0b0f11" }
count_cut      = { fg = "#dfe6ed", bg = "#0b0f11" }
count_selected = { fg = "#dfe6ed", bg = "#0b0f11" }

# Border
border_symbol = "│"
border_style  = { fg = "#dfe6ed" }

# Highlighting
syntect_theme = "~/.config/yazi/theme/current_syntect.tmTheme"
# }}}


# Tabs {{{

[tabs]
active   = { fg = "#a6cbe6", bg = "#0b0f11", bold = true }
inactive = { fg = "#dfe6ed", bg = "#0b0f11" }

# Separator
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# }}}


# Mode {{{

[mode]
normal_main = { fg = "#0b0f11", bg = "#a6cbe6", bold = true }
normal_alt  = { fg = "#a6cbe6", bg = "#0b0f11" }

# Select mode
select_main = { fg = "#0b0f11", bg = "#dadeff", bold = true }
select_alt  = { fg = "#dadeff", bg = "#0b0f11" }

# Unset mode
unset_main = { fg = "#0b0f11", bg = "#dadeff", bold = true }
unset_alt  = { fg = "#dadeff", bg = "#0b0f11" }

# }}}


# Indicator of hovered file {{{

[indicator]
parent  = { reversed = true, fg = "#a6cbe6" }
current = { reversed = true, fg = "#a6cbe6" }
preview = { underline = true, fg = "#a6cbe6" }
padding = { open = "", close = "" }

# }}}


# Status bar {{{

[status]
overall   = { fg = "#dfe6ed", bg = "#0b0f11" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep   = { fg = "#dfe6ed" }
perm_type  = { fg = "#dadeff" }
perm_read  = { fg = "#dadeff" }
perm_write = { fg = "#dadeff" }
perm_exec  = { fg = "#dadeff" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#dadeff", bg = "#0b0f11" }
progress_error  = { fg = "#dadeff", bg = "#0b0f11" }

# }}}


# Which {{{

[which]
cols            = 3
mask            = { bg = "#0b0f11" }
cand            = { fg = "#dadeff" }
rest            = { fg = "#dfe6ed" }
desc            = { fg = "#a6cbe6" }
separator       = "  "
separator_style = { fg = "#dfe6ed" }

# }}}


# Confirmation {{{

[confirm]
border     = { fg = "#a6cbe6" }
title      = { fg = "#a6cbe6" }
body       = { fg = "#dfe6ed" }
list       = { fg = "#dfe6ed" }
btn_yes    = { reversed = true, fg = "#a6cbe6" }
btn_no     = { fg = "#dfe6ed" }
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# }}}


# Spotter {{{

[spot]
border = { fg = "#a6cbe6" }
title  = { fg = "#a6cbe6" }

# Table
tbl_col  = { fg = "#dfe6ed" }
tbl_cell = { fg = "#dadeff", reversed = true }

# }}}


# Notification {{{

[notify]
title_info  = { fg = "#dadeff" }
title_warn  = { fg = "#dadeff" }
title_error = { fg = "#dadeff" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

# }}}


# Picker {{{

[pick]
border   = { fg = "#a6cbe6" }
active   = { fg = "#a6cbe6", bold = true }
inactive = { fg = "#dfe6ed" }

# }}}


# Input {{{

[input]
border   = { fg = "#a6cbe6" }
title    = { fg = "#dfe6ed" }
value    = { fg = "#dfe6ed" }
selected = { reversed = true, fg = "#a6cbe6" }

# }}}


# Completion {{{

[cmp]
border   = { fg = "#a6cbe6" }
active   = { reversed = true, fg = "#a6cbe6" }
inactive = { fg = "#dfe6ed" }

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

# }}}


# Task manager {{{

[tasks]
border  = { fg = "#a6cbe6" }
title   = { fg = "#dfe6ed" }
hovered = { fg = "#a6cbe6", bold = true }

# }}}


# Help menu {{{

[help]
on      = { fg = "#dadeff" }
run     = { fg = "#a6cbe6" }
desc    = { fg = "#dfe6ed" }
hovered = { reversed = true, bold = true, fg = "#a6cbe6" }
footer  = { fg = "#0b0f11", bg = "#dfe6ed" }

# }}}


# File-specific styles {{{

[filetype]
rules = [
	# directories
	{ url = "*/", fg = "#a6cbe6"},
    # files
	{ url = "*", fg = "#a6cbe6"}
]

# }}}


# Icons: {{{

[icon]
conds = [
	# Special files
	{ if = "orphan", text = ""},
	{ if = "link", text = ""},
	{ if = "sticky", text = ""},

	# Fallback
	{ if = "dir & hovered", text = "", fg = "#a6cbe6"},
	{ if = "dir", text = "", fg = "#a6cbe6"},
	{ if = "exec", text = "", fg = "#a6cbe6"},
	{ if = "!dir", text = "", fg = "#a6cbe6"}
]

globs = []
dirs  = []
files = []
exts = []

# }}}