# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#121412

# Main text color
theme[main_fg]=#e2e3de

# Title color for boxes
theme[title]=#e2e3de

# Highlight color for keyboard shortcuts
theme[hi_fg]=#fbfff8

# Background color of selected item in processes box
theme[selected_bg]=#1e201e

# Foreground color of selected item in processes box
theme[selected_fg]=#fbfff8

# Color of inactive/disabled text
theme[inactive_fg]=#8b938b

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#fdfeff

# Background color of the percentage meters
theme[meter_bg]=#8b938b

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#fdfeff

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#5bd0df
theme[mem_box]=#a8f0b7
theme[net_box]=#c6c177
theme[proc_box]=#62cfb4

# Box divider line and small boxes line color
theme[div_line]=#414942

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#a8f0b7
theme[temp_mid]=#dff8d4
theme[temp_end]=#c5b542

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#aceec7
theme[cpu_mid]=#7ed8b6
theme[cpu_end]=#88dcc9

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#5bd0df
theme[free_mid]=#88dcc9
theme[free_end]=#62cfb4

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#7ed8b6
theme[cached_mid]=#62cfb4
theme[cached_end]=#88dcc9

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#b8d79b
theme[available_mid]=#c6c177
theme[available_end]=#c5b542

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#a8f0b7
theme[used_mid]=#aceec7
theme[used_end]=#9febc7

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#b8d79b
theme[download_mid]=#c6c177
theme[download_end]=#c5b542

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#a8f0b7
theme[upload_mid]=#aceec7
theme[upload_end]=#9febc7

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#7ed8b6
theme[process_mid]=#88dcc9
theme[process_end]=#5bd0df
